version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8081:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - auto_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - auto_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - auto_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  auto_net:
    driver: overlay
    attachable: true

volumes:
  jenkins_data:
  registry_data:
  portainer_data:

